/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AutocadDwgRouteImport } from './routes/autocad-dwg'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as InformatiiLegaleRouteImport } from './routes/informatii-legale'
import { Route as InstalatiiElectriceRouteImport } from './routes/instalatii-electrice'
import { Route as InstalatiiTermiceRouteImport } from './routes/instalatii-termice'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MagazinRouteImport } from './routes/magazin'
import { Route as ModelareRevitRouteImport } from './routes/modelare-revit'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PoliticaDeConfidentialitateRouteImport } from './routes/politica-de-confidentialitate'
import { Route as PortofoliuRouteImport } from './routes/portofoliu'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferinteRouteImport } from './routes/referinte'
import { Route as RevitMepRouteImport } from './routes/revit-mep'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermeniSiConditiiRouteImport } from './routes/termeni-si-conditii'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AutocadDwgRoute = AutocadDwgRouteImport.update({
  id: '/autocad-dwg',
  path: '/autocad-dwg',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const InformatiiLegaleRoute = InformatiiLegaleRouteImport.update({
  id: '/informatii-legale',
  path: '/informatii-legale',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalatiiElectriceRoute = InstalatiiElectriceRouteImport.update({
  id: '/instalatii-electrice',
  path: '/instalatii-electrice',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalatiiTermiceRoute = InstalatiiTermiceRouteImport.update({
  id: '/instalatii-termice',
  path: '/instalatii-termice',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinRoute = MagazinRouteImport.update({
  id: '/magazin',
  path: '/magazin',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelareRevitRoute = ModelareRevitRouteImport.update({
  id: '/modelare-revit',
  path: '/modelare-revit',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeConfidentialitateRoute =
  PoliticaDeConfidentialitateRouteImport.update({
    id: '/politica-de-confidentialitate',
    path: '/politica-de-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortofoliuRoute = PortofoliuRouteImport.update({
  id: '/portofoliu',
  path: '/portofoliu',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferinteRoute = ReferinteRouteImport.update({
  id: '/referinte',
  path: '/referinte',
  getParentRoute: () => rootRouteImport,
} as any)
const RevitMepRoute = RevitMepRouteImport.update({
  id: '/revit-mep',
  path: '/revit-mep',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniSiConditiiRoute = TermeniSiConditiiRouteImport.update({
  id: '/termeni-si-conditii',
  path: '/termeni-si-conditii',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/autocad-dwg': typeof AutocadDwgRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/hvac': typeof HvacRoute
  '/informatii-legale': typeof InformatiiLegaleRoute
  '/instalatii-electrice': typeof InstalatiiElectriceRoute
  '/instalatii-termice': typeof InstalatiiTermiceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/magazin': typeof MagazinRoute
  '/modelare-revit': typeof ModelareRevitRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/portofoliu': typeof PortofoliuRoute
  '/privacy': typeof PrivacyRoute
  '/referinte': typeof ReferinteRoute
  '/revit-mep': typeof RevitMepRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/autocad-dwg': typeof AutocadDwgRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/hvac': typeof HvacRoute
  '/informatii-legale': typeof InformatiiLegaleRoute
  '/instalatii-electrice': typeof InstalatiiElectriceRoute
  '/instalatii-termice': typeof InstalatiiTermiceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/magazin': typeof MagazinRoute
  '/modelare-revit': typeof ModelareRevitRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/portofoliu': typeof PortofoliuRoute
  '/privacy': typeof PrivacyRoute
  '/referinte': typeof ReferinteRoute
  '/revit-mep': typeof RevitMepRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/autocad-dwg': typeof AutocadDwgRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/hvac': typeof HvacRoute
  '/informatii-legale': typeof InformatiiLegaleRoute
  '/instalatii-electrice': typeof InstalatiiElectriceRoute
  '/instalatii-termice': typeof InstalatiiTermiceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/magazin': typeof MagazinRoute
  '/modelare-revit': typeof ModelareRevitRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/portofoliu': typeof PortofoliuRoute
  '/privacy': typeof PrivacyRoute
  '/referinte': typeof ReferinteRoute
  '/revit-mep': typeof RevitMepRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/autocad-dwg'
    | '/contact'
    | '/despre'
    | '/hvac'
    | '/informatii-legale'
    | '/instalatii-electrice'
    | '/instalatii-termice'
    | '/llms.txt'
    | '/magazin'
    | '/modelare-revit'
    | '/politica-cookies'
    | '/politica-de-confidentialitate'
    | '/portofoliu'
    | '/privacy'
    | '/referinte'
    | '/revit-mep'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/autocad-dwg'
    | '/contact'
    | '/despre'
    | '/hvac'
    | '/informatii-legale'
    | '/instalatii-electrice'
    | '/instalatii-termice'
    | '/llms.txt'
    | '/magazin'
    | '/modelare-revit'
    | '/politica-cookies'
    | '/politica-de-confidentialitate'
    | '/portofoliu'
    | '/privacy'
    | '/referinte'
    | '/revit-mep'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/autocad-dwg'
    | '/contact'
    | '/despre'
    | '/hvac'
    | '/informatii-legale'
    | '/instalatii-electrice'
    | '/instalatii-termice'
    | '/llms.txt'
    | '/magazin'
    | '/modelare-revit'
    | '/politica-cookies'
    | '/politica-de-confidentialitate'
    | '/portofoliu'
    | '/privacy'
    | '/referinte'
    | '/revit-mep'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutocadDwgRoute: typeof AutocadDwgRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  HvacRoute: typeof HvacRoute
  InformatiiLegaleRoute: typeof InformatiiLegaleRoute
  InstalatiiElectriceRoute: typeof InstalatiiElectriceRoute
  InstalatiiTermiceRoute: typeof InstalatiiTermiceRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MagazinRoute: typeof MagazinRoute
  ModelareRevitRoute: typeof ModelareRevitRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaDeConfidentialitateRoute: typeof PoliticaDeConfidentialitateRoute
  PortofoliuRoute: typeof PortofoliuRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferinteRoute: typeof ReferinteRoute
  RevitMepRoute: typeof RevitMepRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniSiConditiiRoute: typeof TermeniSiConditiiRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocad-dwg': {
      id: '/autocad-dwg'
      path: '/autocad-dwg'
      fullPath: '/autocad-dwg'
      preLoaderRoute: typeof AutocadDwgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatii-legale': {
      id: '/informatii-legale'
      path: '/informatii-legale'
      fullPath: '/informatii-legale'
      preLoaderRoute: typeof InformatiiLegaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalatii-electrice': {
      id: '/instalatii-electrice'
      path: '/instalatii-electrice'
      fullPath: '/instalatii-electrice'
      preLoaderRoute: typeof InstalatiiElectriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalatii-termice': {
      id: '/instalatii-termice'
      path: '/instalatii-termice'
      fullPath: '/instalatii-termice'
      preLoaderRoute: typeof InstalatiiTermiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazin': {
      id: '/magazin'
      path: '/magazin'
      fullPath: '/magazin'
      preLoaderRoute: typeof MagazinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelare-revit': {
      id: '/modelare-revit'
      path: '/modelare-revit'
      fullPath: '/modelare-revit'
      preLoaderRoute: typeof ModelareRevitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-confidentialitate': {
      id: '/politica-de-confidentialitate'
      path: '/politica-de-confidentialitate'
      fullPath: '/politica-de-confidentialitate'
      preLoaderRoute: typeof PoliticaDeConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofoliu': {
      id: '/portofoliu'
      path: '/portofoliu'
      fullPath: '/portofoliu'
      preLoaderRoute: typeof PortofoliuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referinte': {
      id: '/referinte'
      path: '/referinte'
      fullPath: '/referinte'
      preLoaderRoute: typeof ReferinteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revit-mep': {
      id: '/revit-mep'
      path: '/revit-mep'
      fullPath: '/revit-mep'
      preLoaderRoute: typeof RevitMepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-si-conditii': {
      id: '/termeni-si-conditii'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii'
      preLoaderRoute: typeof TermeniSiConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutocadDwgRoute: AutocadDwgRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  HvacRoute: HvacRoute,
  InformatiiLegaleRoute: InformatiiLegaleRoute,
  InstalatiiElectriceRoute: InstalatiiElectriceRoute,
  InstalatiiTermiceRoute: InstalatiiTermiceRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MagazinRoute: MagazinRoute,
  ModelareRevitRoute: ModelareRevitRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaDeConfidentialitateRoute: PoliticaDeConfidentialitateRoute,
  PortofoliuRoute: PortofoliuRoute,
  PrivacyRoute: PrivacyRoute,
  ReferinteRoute: ReferinteRoute,
  RevitMepRoute: RevitMepRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniSiConditiiRoute: TermeniSiConditiiRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
